name: Run Ryanair Price Tracker
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install flyctl
        run: curl -L https://fly.io/install.sh | sh
      - name: Set up flyctl PATH
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH
      - name: Check flyctl version
        run: flyctl version
      - name: Check app status
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl status --app ryanair-tracker-2
      - name: Start Fly.io machine
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl machine start d899046c660d48 --app ryanair-tracker-2
      - name: Wait for machine to start
        run: sleep 10  # Задержка 10 секунд
      - name: Create data directory
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl machine exec d899046c660d48 "mkdir -p /app/data" --app ryanair-tracker-2
      - name: Run script on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl machine exec d899046c660d48 "python /app/ryanair_price_tracker.py" --app ryanair-tracker-2